### ISSUE TITLE
Poison cloud does not linger

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MSCScripts#104]
Cloud fails to apply DoT after initial strike.

**Comment by greatguys1** [comment]
Was not a script issue, and has since been fixed.

**Comment by greatguys1** [comment]
Poison cloud was found again to not apply DoT after the initial strike

**Comment by gossbell** [comment]
The poison clouds lingering effect works but only against "hostile" enemies.

**Comment by greatguys1** [comment]
Thank you for testing this, it will make it easier to narrow down where this issue is coming from.
