### ISSUE TITLE
Calruin2 end boss weapon spawns may be broken.

### ISSUE THREAD

**Issue by Syndel-Birb** [MSRevive/MSCScripts#119]
Tested end boss of Calruin2 3 times. All three times the game claimed it dropped Granite Maul but no drop appeared.

**Comment by Syndel-Birb** [comment]
Just to confirm, proper boss despatch tactic was applied: all three seals activated in order and boss killed by volcano.

**Comment by Syndel-Birb** [comment]
I've created a test version of Calruin2 which should spawn the items in front of you as soon as you walk forwards.
![image](https://user-images.githubusercontent.com/104350464/197391404-2dcd5756-1d27-4d38-bb57-47b236f382fe.png)
[Calruin2.zip](https://github.com/MSRevive/MSCScripts/files/9846528/Calruin2.zip)

Running this confirms the script does run the item picker but is failing to spawn the item.

**Comment by greatguys1** [comment]
Thanks for sumbitting the issue. Ill look into this asap.
