### ISSUE TITLE
Player Bear Model Not Properly Illuminated In Most Cases

### ISSUE THREAD

**Issue by PHILLIPGATLIN** [MSRevive/MSCScripts#128]
When the player activates the special ability of Bear Claws the player model changes into a bear, in most situations this model is not properly illuminated by world lights. I don't know if anything can be done about this, but having correct lighting for this model would be nice.

**Comment by greatguys1** [comment]
It seems to illuminate based off of lighting from the origin (0,0,0) of the map. I dont see why, but I'll investigate to see if it can be fixed script side

**Comment by greatguys1** [comment]
I dont think this can be fixed script side. I think the issue lies in the setfollow scriptcmd.
