### ISSUE TITLE
Oyster needs his new spawning system so that his newer maps will work

### ISSUE THREAD

**Issue by 2cwldys** [MSRevive/MSCScripts#129]
Oyster has recently and casually mentioned to me that in order for his newer maps to work he will need his spawning system recreated. Either directly tied into the quest system by greatguys1, or not sure what the extent of what he needs exactly.

**Comment by greatguys1** [comment]
I have to talk to Oyster directly to find out whats needed. I noticed he laid out some requirements in the discord. I'll make a task list and update this issue with it so we can track progress.

**Comment by greatguys1** [comment]
As a note to myself: I got the maps, just test them & see what scripts are missing. See if the scripts can be dropped in, but if they dont work they will need to be fixed. Also look into the spawn system that the maps depend on.

**Comment by greatguys1** [comment]
Sorry for delay. Having to focus on fixes and quality of life. Will try to come around to this.
