### ISSUE TITLE
Lightning storm lasts until weapon swap, so it last forever with the new fizzle change

### ISSUE THREAD

**Issue by Dark4557** [MSRevive/MSCScripts#133]
Gotta put a general timer on the lightning storm when used, instead of having it coincide with your spell in hand

**Comment by SaintWish** [comment]
An alternative solution is to make it cost more mana per second.

**Comment by greatguys1** [comment]
I believe it does cost mana per second. The storm should expire after not being moved for a time.

**Comment by greatguys1** [comment]
Ope, my bad, I missed the "more" in more mana per second. Yeah I agree that it should, but not as an alternative solution. I think it should go along with it.
