### ISSUE TITLE
Healing Wave doesn't heal when player kills > 0

### ISSUE THREAD

**Issue by CrashWolf** [MSRevive/MSCScripts#135]
Healing wave (both spell and fshard form) does not heal players when pvp is disabled. Still works on npcs as expected though

**Comment by CrashWolf** [comment]
After some experimentation, some players are able to heal with both, whereas others are not. The only thing I can see that might be causing it is player kills changing the user's status, otherwise *shrug*

**Comment by greatguys1** [comment]
Wow... will fix.

**Comment by CrashWolf** [comment]
After further testing, you can't heal with healing wave in pvp, and without pvp on players that have player kills can't heal others with either sword or spell.

**Comment by greatguys1** [comment]
I think this last push fixed it. Need to test with somebody
