### ISSUE TITLE
Death message erroneously reports spider protection removal

### ISSUE THREAD

**Issue by Uberzolik** [MSRevive/MSCScripts#143]
Tested on a completely new character as well as my relatively old one, both of them always display "The protection from spider magic fades." on death.

![image](https://user-images.githubusercontent.com/12388394/199149053-aa0da76d-9259-43ca-bd01-b98d715ae101.png)

**Comment by greatguys1** [comment]
The spider protection potion has always functioned oddly. Hopefully the effect still works and this is just a message that gets erroneously sent. Thanks for the report.

**Comment by Tsarenir** [comment]
This was also happening to me last night on my main character, unfortunately I don't remember if it was happening over the weekend but funnily enough I did drink a spider protection potion toward the end of Sunday.

**Comment by frendship-loost** [comment]
![image](https://user-images.githubusercontent.com/85242183/199918060-de7dd35f-9279-4fd6-9095-eb0c3c5fb805.png)

I get the same message on my main character (fairly old file). I maybe drank 1 spider potion a few weeks ago, and before that who knows? years? never?

On a side-note it really strikes me as odd that there is specifically a spider protection potion, when they essentially disappear after early-game. And you don't find many of those potions in the early game either.
