### ISSUE TITLE
Corrodinator doesn't appear to increase Poison Cloud poison duration

### ISSUE THREAD

**Issue by CrashWolf** [MSRevive/MSCScripts#167]
It looks like it works on Poison spell, but Poison Cloud's poison dot itself seems to last a very short time, so it may even be shortened by corrodinator.

**Comment by CrashWolf** [comment]
Upon further inspection, it appears that the actual problem I was facing was that poison cloud just doesn't have much duration to it. The corrodinator is doing what it's supposed to, but poison cloud has nowhere near as many ticks as I thought it would, especially the linger effect which only has 2 base ticks before ending.

**Comment by greatguys1** [comment]
Oh interesting. Can you explain in a little more detail, as im having trouble fully understanding? From what it sounds like, the poison cloud needs a buff.

**Comment by CrashWolf** [comment]
As it stands, Poison Cloud works much like Blizzard. The initial hit has more dot damage hits (like 10 or so), aka ticks, that also do more damage than the linger effect inflicts. Blizzard however does 4 ticks on linger, whereas Poison Cloud's linger only does 2. So an enemy that walks through the cloud will usually have it inflicted on them two or more times before they escape it, rather than just having one long-lasting effect.
Personally, I would have the linger and base hit have the same damage and probably even duration as each other (taking on the base hit's effect), so that players aren't forced to coerce enemies out of the cloud so they can be hit with a new one for reasonable damage, especially since Poison Cloud costs like 40 mana to cast.
Different topic, but Blizzard could probably do with the same upgrade, although that's debatable because ice dot also has a secondary effect (slow) that poison does not.

**Comment by greatguys1** [comment]
Poison cloud dot duration was buffed by 3x in this commit: https://github.com/MSRevive/MSCScripts/commit/b4bf3d06f2bf0efd95f741435ae22beee7e9f6d4
