### ISSUE TITLE
Orion bow projectile should not strike the same enemy twice. Additionally, it should not expire when it hits the bbox of an enemy

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MSCScripts#192]

**Comment by Syndel-Birb** [comment]
If Orion bow is changed to not hit the same enemy twice it's going to need a big damage buff or mana cost reduction. Part of what makes the Orion bow worth having is this ability.

**Comment by greatguys1** [comment]
I may consider and test a few things before committing to this. But a buff would be warranted from a change like this

**Comment by greatguys1** [comment]
The bow was changed to have the ball size get reduced for each strike. It can still strike the same enemy twice. c53c646
