### ISSUE TITLE
Mummies cause no free edicts fatal error

### ISSUE THREAD

**Issue by Uberzolik** [MSRevive/MSCScripts#209]
Has happened twice in deraliasewers, people have reported it happening in catacombs as well. Shortly after the mummies start spawning, the server crashes with the following error: 

![image](https://user-images.githubusercontent.com/12388394/205511627-05864301-e4d2-48f5-a77b-81206b25abee.png)

Not entirely clear which of the mummies it is, though.

**Comment by greatguys1** [comment]
How many people were on the server when this happened? Ive done several solo runs on FN without any errors.

**Comment by Uberzolik** [comment]
We had 6-7 people, it was during one of the discord events. Not sure about the catacombs ones, or the other deraliasewers run that reported it.

**Comment by greatguys1** [comment]
No free edicts usually indicates that there are too many entities existing at once. This may be tricky with no clear solution.

**Comment by greatguys1** [comment]
Something that was mentioned before was that launching servers with the parameter `-num_edicts 2048` will help mitigate this issue. But this is up to server owners to do all on their own. 
As a note for that launch param, setting it higher can cause issues since that is the engine limitation.

**Comment by greatguys1** [comment]
It seems to be a crash related to a script that holds someone in place. I'm not sure if that's the only issue though, or why it reported no free edits.
