### ISSUE TITLE
Forgetfulness Potion GUI not working?

### ISSUE THREAD

**Issue by RWGryphon** [MSRevive/MSCScripts#211]
Just had Rust use two forgetfulness potions and they failed to pop up the GUI. It hasn't worked twice now and we're out of forgetfulness potion reserves, I think it's pretty broken right now but I'm not sure why.

**Comment by greatguys1** [comment]
This came from the changes to the voting system (like votemap). Thinking about it, I think I know where I created this issue during these changes, despite trying to accommodate it. It should be fixed by next patch.
