### ISSUE TITLE
Shops become unusable if a player with a full inventory tries to open one

### ISSUE THREAD

**Issue by noijom** [MSRevive/MSCScripts#215]

**Comment by greatguys1** [comment]
I don't know if this is intended or not. I'll have to look at behavior to see if it's a good idea to enable that.

**Comment by fegged** [comment]
Same thing happens when someone is in a shop and another tries to open, breaks the NPC entirely.

**Comment by greatguys1** [comment]
I misunderstood the issue initially. While players shouldn't be able to do actions that get them items with a full inventory, the shop locking up is obviously not intended.
