### ISSUE TITLE
Rejuvenate Spell Name Mismatch

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MSCScripts#218]
Hard to explain, but the names of the rejuvenation spell are different in the tomed and learned versions. I'm not 100% sure if it is also misspelled on the scroll version as I haven't yet seen one.

Tome item itself is called "A Tome of Rejuvenate" - would it be better called Rejuvenation? Here's the tome:
https://steamuserimages-a.akamaihd.net/ugc/2008073454943482001/9BA7EE68BBC1E26FB67E380EDAF37AF93C4F2332/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

Here's "Rejuvenate" under the tomed/learned spells selection, calling it "Rejuvination" - Should be called either Rejuvenate or Rejuvenation, whichever naming convention is chosen.
https://steamuserimages-a.akamaihd.net/ugc/2008073454943484998/C466CBFDEAF68167A5220220FA63049944489644/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by greatguys1** [comment]
Fixed in Alpha-NewSpells
