### ISSUE TITLE
Most Resistances Lost Upon Dying

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MSCScripts#225]
Upon death, resistances are typically lost and the associated items need to be re-equipped in order to gain their bonuses again.

These include Helmet of Fire/Cold Resist, Phoenix Armor, and Ring of Grounding. 

However, physical damage reduction armors such as Lord Vecilus' Mail will continue giving damage reduction. Another exception is Acid Plate, where the poison and acid resistance are maintained throughout death and does not need to be re-equipped. Helmet of Stability seems to also NOT lose its resistance to stun through death.

I have not been able to test any other amors/items yet aside from those listed here.

**Comment by greatguys1** [comment]
This happens to most elemental resistances in the current steam build. This has been fixed in the next patch:
https://github.com/MSRevive/MSCScripts/issues/173
