### ISSUE TITLE
Hoarfrost Ice Circle doesn't reward Exp

### ISSUE THREAD

**Issue by CrashWolf** [MSRevive/MSCScripts#233]

**Comment by greatguys1** [comment]
It might be going into the wrong skill, this was an issue in classic for a long time.

**Comment by CrashWolf** [comment]
![20230101203500_1](https://user-images.githubusercontent.com/78764490/210456255-2cbf5ff7-01fa-4fb2-87f8-350ddae16904.jpg)
Nope, just doesn't give any exp at all.

**Comment by greatguys1** [comment]
I see. Fixed.
https://github.com/MSRevive/MSCScripts/commit/afcc85e166baaf2516f823572c3fdf4a7185b245
