### ISSUE TITLE
Undercliffs + Underpath Maps Need Hidden Tag

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MSCScripts#239]
Undercliffs and Underpath can both be vote-map to, but show a black screen upon loading in due to not having touched proper transition. They should be considered hidden and not able to be vote-map to in the first place.

**Comment by Dark4557** [comment]
https://github.com/MSRevive/MSCScripts/commit/ccb19cc60b74bfe57b6e7c6b766222639c76f14e
