### ISSUE TITLE
Vendors Cease to Function if One Player Attempts to Interact While Another has Buy Menu Open

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MSCScripts#241]
This has been a long-standing one. Easy to recreate; just go to a vendor (helena, for example) and have one character open the buy menu. While open, have another character attempt to also open the buy menu. The vendor will then be locked and can no longer be interacted with.

**Comment by greatguys1** [comment]
Oof, this one seems to come back every now and again.

**Comment by greatguys1** [comment]
Copy of this issue: https://github.com/MSRevive/MSCScripts/issues/215
