### ISSUE TITLE
Polearms Deal Ludicrous Damage to Breakables

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MSCScripts#242]
Lots of maps use func_breakable to section off parts of the map or limit player movement, or just for map functionality. Polearm damage multiplication due to range causes them to break these brushes with ease, when normally they shouldn't be able to do so.

Most notable areas to test these are Bludgeon area in Lodagond, with the descending stairwell and the 4 layer crystal. As well as Curse of the Bear Gods with the spider area; the walls blocking the chest can be broken and the entire spider encounter can be skipped.

**Comment by greatguys1** [comment]
This can be fixed. The breakables can still be broken, but it will take a lot more effort (maybe not even worth it). Thanks for the report.
