### ISSUE TITLE
Cobra Skin armor doesn't seem to give resists

### ISSUE THREAD

**Issue by ArcanumHominem** [MSRevive/MSCScripts#267]
Ran islesofdread1 with Cobra Skin armor on and noticed I was getting poisoned rather frequently.  Upon further inspection I noticed that even if it rolled under the listed 75 poison value it would still apply the dot (and drunk effect if it was an enhanced projectile from the zombies).
![normal poison](https://user-images.githubusercontent.com/34590399/218788851-eba29c0c-dbcd-4c87-9bdb-4520e6fbf45c.jpg)
![drunk poison](https://user-images.githubusercontent.com/34590399/218788871-86ba3373-a5cc-4f11-b449-8f78282c5cfa.jpg)

**Comment by ArcanumHominem** [comment]
Heard that this was supposedly known about but didn't find anything when searching for "resist" or "debuff" under the main and script branches so I'll leave it up for now and you can take this down if needed.

**Comment by greatguys1** [comment]
This is related to how DoTs calculate and deal damage. It's an odd bug.
