### ISSUE TITLE
Create custom Sophie script (dog in Gertenheld_Forest2)

### ISSUE THREAD

**Issue by Dridje** [MSRevive/MSCScripts#269]
Low priority, I can probably work on this myself in a few days.  It's about time one is made that cannot be killed as Sophie is a memorial to my IRL dog and makes me sad to see people kill her. Q.Q

**Comment by greatguys1** [comment]
I made an addparam so you can make the npc invulnerable:
`toggle_invincible - makes the monster invincible if they are not, or makes them vulnerable if they are.`

**Comment by greatguys1** [comment]
I believe the addparam was applied and the map was updated. Closing issue.
