### ISSUE TITLE
Orcs drop gold on Listen servers but not Dedicated servers

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MSCScripts#276]
Spin up a listen server on Heras or Chapel and kill the orcs. You're able to press X and loot their gold. Join a dedicated server and you are no longer able to do so.

I'm not sure if this is a FuzzNet functionality or what.

**Comment by greatguys1** [comment]
This is very odd. I know there is a way for scripts to check if theyre on a dedicated server, but that would be very odd to program in.

**Comment by greatguys1** [comment]
60d4a2f attempt to fix
