### ISSUE TITLE
Some spawn triggers don't work in catacombs

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MSCScripts#28]
For example the wall to the portals in the mummy area never break like they should. Fegged can provide more information.

**Comment by fegged** [comment]
First left room does not trigger the path once completed (blood through the gaps), blocking the rest of the map

**Comment by greatguys1** [comment]
I was able to complete the map with no problems. It might have been fixed in an unknown commit. Can someone else test to confirm?

**Comment by SaintWish** [comment]
Just confirmed with the latest scripts it works fine now.
