### ISSUE TITLE
Pelts cause dual wield penalty

### ISSUE THREAD

**Issue by Tsarenir** [MSRevive/MSCScripts#285]
Pelts use a prefix that isn't checked in the dual wield penalty statement
![image](https://user-images.githubusercontent.com/39228913/222832292-88150848-a0e4-4a09-83f4-e1c433b16ec7.png)
![image](https://user-images.githubusercontent.com/39228913/222832322-ec65a78d-b00a-49c0-8cc7-e68ece07d9e0.png)

**Comment by Dark4557** [comment]
834b97a
