### ISSUE TITLE
Ihothor's head didn't drop on The_Wall.

### ISSUE THREAD

**Issue by ArcanumHominem** [MSRevive/MSCScripts#293]
Ran The_Wall and the three mini-bosses before Ihothor all dropped heads that I was able to pick up.  After killing Ihothor there was no head drop from where he had died.

**Comment by greatguys1** [comment]
Fixed in https://github.com/MSRevive/MSCScripts/commit/d063d7e8aa6e08c8dba85facb3b8df2d61d0d466
