### ISSUE TITLE
Giant spider eggs in Thornlands->Spitting Spider room don't seem to spawn anything

### ISSUE THREAD

**Issue by thesupersoup** [MSRevive/MSCScripts#309]
These eggs didn't spawn any spiders, or the item I seem to recall from MSC

![20230705225326_1](https://github.com/MSRevive/MasterSwordRebirth/assets/40295603/e0963225-a6c8-41a3-b9f7-2933db0c0ed1)

**Comment by Dridje** [comment]
This is actually a mapping "issue".  Not quite an issue tbh.  At the present, the potion easter egg has been added and still debating on adding the spiders back or not.  Will decide by tomorrow when I take a look at https://github.com/MSRevive/map-sources/issues/61

**Comment by Dridje** [comment]
I have decided for the time being to just leave it as is.  This can be closed @SaintWish
