### ISSUE TITLE
Oceancrossing Cannon Bugged

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MSCScripts#32]
When the invading ship has been thwarted, the cannon used to sink the opposing ship will cause the projectile to detonate immediately after firing, preventing the climax of the map from succeeding and consequently spawning the extra chest.

**Comment by greatguys1** [comment]
This is a script issue. Moved it to the script repo

**Comment by greatguys1** [comment]
Fixed in https://github.com/MSRevive/MSCScripts/commit/a060ba49f0865e876c63a6679d50c86ee0f3e80c
