### ISSUE TITLE
Charged Attack Preventing any Attack

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MSCScripts#33]
This is primarily found on small arms weapons. If you have the proficiency to wield the weapon, but not yet high enough to use the charge attack, you cannot attack at all without turning off ms_autocharge. It will constantly try to charge through first and second charge but nothing will happen and you cannot attack.

Setting ms_autocharge to 0 allows the player to use the weapons again until their proficiency allows them to charge attack, then behavior occurs as it should.

**Comment by greatguys1** [comment]
This affects any item that allows a charge ability above the first charge, if the first charge isn't unlocked yet.

**Comment by greatguys1** [comment]
Fixed some smallarms & polearms. Weapons that are still affected are things like the Acid Lance, if you have the third charge unlocked via spellcasting, but do not have the first charge unlocked.
