### ISSUE TITLE
Skeleton-type Enemies (Tested in Thornlands) Reset Their HP to Full When Resurrecting.

### ISSUE THREAD

**Issue by RWGryphon** [MSRevive/MSCScripts#37]
- For some reason, whenever I kill a skeleton, the skeleton will fall down and lay on the ground with a health value of 35/70 hp. However, before the skeleton stands up, their health value is reset to 70/70. Skeleton revival behavior is not operating properly, and heals skeletons to full health when they get up again.

- How does this behave with other skeleton types? 

(Notice: This has been tested in Thornlands on a new character. I am going through standard progression.)

**Comment by greatguys1** [comment]
Fixed, skeletons now have their hp halved each time they revive, just like their xp.
