### ISSUE TITLE
m2_quest: sylphiel can be lured out of the house and hidden

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MSCScripts#38]
Talking to her redirects her, can she can be lured out of the house and put somewhere.

**Comment by greatguys1** [comment]
It might just be best to put a monster clip in the stairway or doorway of the house.

**Comment by Charles445** [comment]
This seems to have to do with her animations

I had some luck adding
`setidleanim ANIM_IDLE`
After this line
https://github.com/MSRevive/MSCScripts/blob/MSCScript-alpha/scripts/m2_quest/sylphiel.script#L175
So when she stops running in her circle, the idle animation goes back to ANIM_IDLE
It'll get set to walk again when she continues circling

**Comment by greatguys1** [comment]
Fxied in https://github.com/MSRevive/MSCScripts/pull/83
