### ISSUE TITLE
Chests/keledros.script Does not Include Blizzard as a Reward In the Chest.

### ISSUE THREAD

**Issue by RWGryphon** [MSRevive/MSCScripts#56]
As the issue states, it appears blizzard was removed from the list of rewards sometime in the past. No idea why. Quite strange. See lines 2 and 3.

We've been running the map for quite some time now and I had a suspicion to check the scripts and, alas, the blizzard scroll or tome is not listed in the rewards.

**Comment by greatguys1** [comment]
As of MSClassics last release, it has not been in the loot pool. I'm not sure which version it was removed in, but it'd be nice to know. Seeing as he casts blizzard anyways, he should drop it.

**Comment by greatguys1** [comment]
Added in this commit:
https://github.com/MSRevive/MSCScripts/commit/0f77709937703daf7572f587c25319acdb2572c4

**Comment by RWGryphon** [comment]
So, I know that when I played the old MSClassic, he did in fact drop blizzard at the time, so I have no idea when it was removed... But I KNOW it's in the loot pool. There's no way it isn't.

**Comment by greatguys1** [comment]
If you're talking about MSClassic version nov2015a, it is not in the loot pool in that version. I imagine it would've been in some version prior, but yeah, it was probably removed at some point.
