### ISSUE TITLE
Replace bloodstone ring ability

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MSCScripts#62]
As players can see monster's hp by default now, the bloodstone ring is currently useless. We need to replace it to do something useful now.

**Comment by Tsarenir** [comment]
This might be somewhat controversial in the grand scheme, at least as the game stands presently (or, pre- any balancing adjustments begin), but I have believed for a long time and had spoken to some players in-game over the weekend that seemed to agree, that it would be nice to see more innate health regeneration available in the game. I've also advocated for, probably years ago at this point, both more magical jewelry/trinkets and specifically a health regeneration piece of jewelry, and given the Bloodstone ring's theme, status and involved questline, I believe it'd be a great item to consider reconfiguring in this way. I don't mean anything like the Demon Bludgeon, rage pots, regen pots or sylph soup, just something simple like what you get from holding a Felewyn Shard set to holy mode, something like 5HP / second - maybe a little more, to make it impactful.

**Comment by greatguys1** [comment]
Yeah, players seem to agree so ill make it have health regen.

**Comment by Tsarenir** [comment]
I like capping it at Div 30 with a rate of growth like what was stated, feels like the perfect range for it to be coming online at each breakpoint. in my opinion however, while 2HP/s might help mid-level characters feel a little more comfort, 3HP/s does not sound impactful in the end-game. It's nice to have certainly, and I am interested to see how it plays as it can be adjusted.

**Comment by greatguys1** [comment]
Updated bloodstone ring in the last commit. +1%hp per regen tick. -6 seconds per regen tick. Players can now see monster healthbar by default. Potentially more changes to come, but for now we see how this change goes.

**Comment by greatguys1** [comment]
Will be marking this as completed in a few days if there is no more input.
