### ISSUE TITLE
Transition fails if there is a player on the server that hasn't selected their character and they do not vote

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MSCScripts#70]

**Comment by greatguys1** [comment]
I'm not sure what this means, can you explain the issue in more detail?

**Comment by SaintWish** [comment]
We can start a transition map vote (like lodagond-3) but if there's a player on the server but hasn't selected their character and they do not vote (atleast when we ran into said issue) the map vote will not go through at all.
