### ISSUE TITLE
Orc_For goblin pouncer is un-attackable while he has someone pounced.

### ISSUE THREAD

**Issue by frendship-loost** [MSRevive/MSCScripts#94]
Title. Been a bug for years apparently.

***Also the bone abomination final boss gives total crap exp.
**** Also the spawn transition of orc_for should connect to thornlands_north and not regular thornlands.

**Comment by greatguys1** [comment]
Fixed. He can now have DoTs applied from the person he is attacking, and can directly be damaged by teammates. He also drops off after 20 seconds instead of till death.

**Comment by greatguys1** [comment]
The second issues was separated and created as its own issue in the proper repo. The third issue is already documented in the proper repo.
