### ISSUE TITLE
If you're wearing item with resist and get another one you loose your resist

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MSCScripts#97]
For example if you're wearing a fire helm and you get a fire helm (AKA you hold a fire helm in your hand) you loose your resist.

**Comment by greatguys1** [comment]
Yikes. I think I have an idea of where this issue may be located.

**Comment by greatguys1** [comment]
This doesn't happen with all armor. Paura and Faura does not have this issue, but the Venom Helmet does. Issue may not be as straight forward as I think.
